# site settings

title: Chaehyun Lim
description: Do my best in what I want to do
taglong: Do my best in what I want to do
tagshort: Online CV
url: https://bkindtoevery1.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/bkindtoevery1/bkindtoevery1.github.io

# author settings

author:
  name: Chaehyun Lim
  email: chayhyeon@gmail.com
photo: /assets/jpg/profile_photo.jpg

# social media links

social:
  mail: chayhyeon@gmail.com
  github: bkindtoevery1
  instagram: chayhyeon
  linkedin: chaehyun-lim-3003142a1
  facebook: 100016818703054

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
